/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/example/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items */
        get: operations["Items.list"];
        put?: never;
        /** Create an item */
        post: operations["Items.create"];
        /** Bulk delete by ids */
        delete: operations["Items.bulkDelete"];
        options?: never;
        head?: never;
        /** Bulk partial update */
        patch: operations["Items.bulkUpdate"];
        trace?: never;
    };
    "/example/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an item */
        get: operations["Items.show"];
        put?: never;
        post?: never;
        /** Delete an item */
        delete: operations["Items.delete"];
        options?: never;
        head?: never;
        /** Update an item */
        patch: operations["Items.update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PasswordCredentialsDto: {
            /** @example ada@example.com */
            email?: string;
            /** @example +15551212000 */
            phone?: string;
            /** @example correct horse */
            password: string;
        };
        SessionRoleDto: {
            /** @example owner */
            slug: string;
            /**
             * @example {
             *       "en": "Owner"
             *     }
             */
            label: {
                [key: string]: string;
            };
        };
        SessionUserDto: {
            id: string;
            /** @example ada@example.com */
            email: string | null;
            /** @example +15551212000 */
            phone: string | null;
            roles: components["schemas"]["SessionRoleDto"][];
        };
        SessionResponseDto: {
            /** @example success */
            status: string;
            /** @example Registered */
            message: string;
            data: components["schemas"]["SessionUserDto"] | null;
        };
        PaginationMetaDto: {
            /** @example 50 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 10 */
            limit: number;
            /** @example 5 */
            totalPages?: number;
        };
        ListFilterFieldDto: {
            /** @example name */
            field: string;
            /**
             * @example string
             * @enum {string}
             */
            type: "string" | "number" | "boolean" | "date" | "enum" | "id";
            /**
             * @example [
             *       "$eq",
             *       "$like",
             *       "$in",
             *       "$isNull"
             *     ]
             */
            operators: ("$eq" | "$like" | "$gte" | "$lte" | "$in" | "$isNull")[];
            /**
             * @example [
             *       "active",
             *       "draft"
             *     ]
             */
            enumValues?: string[];
            /** @example categories */
            foreignResourceKey?: string;
        };
        ApiMetaDto: {
            pagination?: components["schemas"]["PaginationMetaDto"];
            /** @description Filterable fields and allowed operators for this list resource */
            filterOptions?: components["schemas"]["ListFilterFieldDto"][];
        };
        ApiSuccessResponseDto: {
            /** @example success */
            status: string;
            /** @example Operation successful */
            message: string;
            meta?: components["schemas"]["ApiMetaDto"];
        };
        ItemResponseDto: {
            id: string;
            /**
             * @example {
             *       "ar": "منتج",
             *       "en": "Item"
             *     }
             */
            name: Record<string, never>;
            /** @example SKU-1 */
            sku: string;
            /** @example 10 */
            price: number;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "ACTIVE" | "ARCHIVED";
            createdAt: string;
            updatedAt: string;
        };
        ApiFieldErrorDto: {
            /** @example email */
            field: string;
            /** @example email must be a valid email address */
            message: string;
            /** @example isEmail */
            code?: string;
        };
        ApiErrorDto: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example Validation failed */
            message: string;
            details?: components["schemas"]["ApiFieldErrorDto"][];
        };
        ApiErrorResponseDto: {
            /** @example error */
            status: string;
            /** @example Validation failed */
            message: string;
            /**
             * @description Always null on error responses
             * @default null
             * @example null
             */
            data: Record<string, never> | null;
            error: components["schemas"]["ApiErrorDto"];
        };
        CreateItemDto: {
            /**
             * @example {
             *       "ar": "منتج",
             *       "en": "Item"
             *     }
             */
            name: Record<string, never>;
            /** @example SKU-1 */
            sku: string;
            /** @example 10 */
            price: number;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status?: "DRAFT" | "ACTIVE" | "ARCHIVED";
        };
        UpdateItemDto: {
            /**
             * @example {
             *       "ar": "منتج",
             *       "en": "Item"
             *     }
             */
            name?: Record<string, never>;
            /** @example SKU-1 */
            sku?: string;
            /** @example 20 */
            price?: number;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status?: "DRAFT" | "ACTIVE" | "ARCHIVED";
        };
        BulkDeleteBodyDto: {
            /**
             * @example [
             *       "018e1234-abcd-7000-a001-000000000001"
             *     ]
             */
            ids: string[];
        };
        BulkErrorDto: {
            id?: string;
            /** @example Resource not found */
            message: string;
        };
        BulkResultResponseDto: {
            /** @example 5 */
            total: number;
            /** @example 4 */
            succeeded: number;
            /** @example 1 */
            failed: number;
            errors: components["schemas"]["BulkErrorDto"][];
        };
        BulkUpdateItem: {
            /**
             * @example {
             *       "ar": "منتج",
             *       "en": "Item"
             *     }
             */
            name?: Record<string, never>;
            /** @example SKU-1 */
            sku?: string;
            /** @example 20 */
            price?: number;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status?: "DRAFT" | "ACTIVE" | "ARCHIVED";
            /** @example 018e1234-abcd-7000-a001-000000000001 */
            id: string;
        };
        BulkUpdateBody: {
            /** @description Items to update. Each item is { id, ...partial update fields }. */
            items: components["schemas"]["BulkUpdateItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "Health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordCredentialsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    "Auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordCredentialsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    "Auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    "Auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    "Auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    "Items.list": {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Field name to sort by */
                sortField?: string;
                sortOrder?: "asc" | "desc";
                /** @description Full-text search keyword */
                search?: string;
                /** @description Comma-separated field names to search within (e.g. name,symbol) */
                searchIn?: string;
                /** @description Structured filters. Example: filters[sku][$like]=sample-sku&filters[status][$eq]=DRAFT */
                filters?: {
                    /**
                     * @description Filter on `sku` (string)
                     * @example {
                     *       "$like": "sample-sku"
                     *     }
                     */
                    sku?: {
                        $eq?: string;
                        /** @example sample-sku */
                        $like?: string;
                        $in?: string[];
                        /** @enum {boolean} */
                        $isNull?: true;
                    };
                    /**
                     * @description Filter on `status` (enum)
                     * @example {
                     *       "$eq": "DRAFT"
                     *     }
                     */
                    status?: {
                        /**
                         * @example DRAFT
                         * @enum {string}
                         */
                        $eq?: "DRAFT" | "ACTIVE" | "ARCHIVED";
                        $in?: ("DRAFT" | "ACTIVE" | "ARCHIVED")[];
                        /** @enum {boolean} */
                        $isNull?: true;
                    };
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        data?: components["schemas"]["ItemResponseDto"][];
                        meta?: {
                            pagination?: {
                                /** @example 0 */
                                total?: number;
                                /** @example 1 */
                                page?: number;
                                /** @example 10 */
                                limit?: number;
                                /** @example 0 */
                                totalPages?: number;
                            };
                            /**
                             * @example [
                             *       {
                             *         "field": "sku",
                             *         "type": "string",
                             *         "operators": [
                             *           "$eq",
                             *           "$like",
                             *           "$in",
                             *           "$isNull"
                             *         ]
                             *       },
                             *       {
                             *         "field": "status",
                             *         "type": "enum",
                             *         "operators": [
                             *           "$eq",
                             *           "$in",
                             *           "$isNull"
                             *         ],
                             *         "enumValues": [
                             *           "DRAFT",
                             *           "ACTIVE",
                             *           "ARCHIVED"
                             *         ]
                             *       }
                             *     ]
                             */
                            filterOptions?: unknown[];
                        };
                    };
                };
            };
            /** @description JWT token is missing, expired, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Insufficient permissions to perform this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The requested resource was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Request body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description An unexpected internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    "Items.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        data?: components["schemas"]["ItemResponseDto"];
                    };
                };
            };
            /** @description JWT token is missing, expired, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Insufficient permissions to perform this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The requested resource was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Request body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description An unexpected internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    "Items.bulkDelete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteBodyDto"];
            };
        };
        responses: {
            /** @description Bulk delete result ({ total, succeeded, failed, errors }) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResultResponseDto"];
                };
            };
        };
    };
    "Items.bulkUpdate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateBody"];
            };
        };
        responses: {
            /** @description Bulk partial-update result ({ total, succeeded, failed, errors }) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResultResponseDto"];
                };
            };
        };
    };
    "Items.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        data?: components["schemas"]["ItemResponseDto"];
                    };
                };
            };
            /** @description JWT token is missing, expired, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Insufficient permissions to perform this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The requested resource was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Request body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description An unexpected internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    "Items.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JWT token is missing, expired, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Insufficient permissions to perform this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The requested resource was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Request body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description An unexpected internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    "Items.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemDto"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        data?: components["schemas"]["ItemResponseDto"];
                    };
                };
            };
            /** @description JWT token is missing, expired, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Insufficient permissions to perform this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The requested resource was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Request body validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description An unexpected internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
}
