// AUTO-GENERATED by `pnpm generate` (openapi-typescript). Do not edit by hand.
export type paths = Record<string, never>;
export type components = { schemas: Record<string, never> };
export type operations = Record<string, never>;
